In [50]:
import pandas as pd
import numpy as np 
from pathlib import Path

from IPython.display import display

In [51]:
data_path = Path("../data/raw/datafile.xlsx")
print("File path:", data_path.resolve())
print("File exists:", data_path.exists())

File path: /Users/sourabh/Desktop/road-accidents-india-analysis/data/raw/datafile.xlsx
File exists: True

In [52]:
excel_file = pd.ExcelFile(data_path, engine="openpyxl")
print("Sheet names:", excel_file.sheet_names)

Sheet names: ['Worksheet']

In [53]:
raw_df = pd.read_excel(
    data_path,
    sheet_name="Worksheet",
    header=None,
    engine='openpyxl'
)

print("Dataset shape:", raw_df.shape)
display(raw_df.head(10))

Dataset shape: (38, 17)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,Sl. No.,State/UT,State / UT - wise Total Number of Road Acciden...,State / UT - wise Total Number of Road Acciden...,State / UT - wise Total Number of Road Acciden...,State / UT - wise Total Number of Road Acciden...,State / UT - wise Total Number of Road Acciden...,Share of States / UTs in Total Number of Road ...,Share of States / UTs in Total Number of Road ...,Share of States / UTs in Total Number of Road ...,Share of States / UTs in Total Number of Road ...,Total Number of Accidents Per Lakh Population ...,Total Number of Accidents Per Lakh Population ...,Total Number of Accidents Per Lakh Population ...,Total Number of Accidents Per Lakh Population ...,"Total Number of Road Accidents per 10,000 Vehi...","Total Number of Road Accidents per 10,000 Km o..."
1,1,Andhra Pradesh,21556,21249,19949,19557,9,5.2,4.6,4.2,4,40.8,40.1,37.5,36.7,14.2,1098.5
2,2,Arunachal Pradesh,283,227,287,277,27,0.1,0,0.1,0.1,18.5,14.7,18.4,17.6,6.2,42.8
3,3,Assam,7411,7023,7421,7848,16,1.8,1.5,1.5,1.6,21.1,19.9,20.8,21.8,15.6,140.1
4,4,Bihar,9553,10801,11014,11610,14,2.3,2.3,2.3,2.4,7.8,8.6,8.7,9,9.2,357.5
5,5,Chhattisgarh,12375,13279,13468,14857,11,3,2.9,2.8,3,42,44.5,44.6,48.7,17,1171.9
6,6,Goa,2849,3011,2846,2682,21,0.7,0.7,0.6,0.5,182.7,192.2,180.7,169.4,26.6,1534.3
7,7,Gujarat,15186,15751,16349,15588,10,3.7,3.4,3.4,3.2,21.8,22.3,22.9,21.5,5.4,588.4
8,8,Haryana,9933,10429,10463,9806,15,2.4,2.3,2.2,2,33.7,34.9,34.6,32.1,12.1,1691
9,9,Himachal Pradesh,2404,2597,2253,2156,22,0.6,0.6,0.5,0.4,32.5,34.9,30.2,28.7,15.2,382.9

In [54]:
df = pd.read_excel(
    data_path,
    sheet_name='Worksheet',
    header=0,
    engine='openpyxl'
)

print("Dataset shape after using first row as header:", df.shape)

Dataset shape after using first row as header: (37, 17)

In [55]:
for index, column in enumerate(df.columns):
    print(index, repr(column))

0 'Sl. No.'
1 'State/UT'
2 'State / UT - wise Total Number of Road Accidents during - 2021'
3 'State / UT - wise Total Number of Road Accidents during - 2022'
4 'State / UT - wise Total Number of Road Accidents during - 2023'
5 'State / UT - wise Total Number of Road Accidents during - 2024 - Number'
6 'State / UT - wise Total Number of Road Accidents during - 2024 - Rank'
7 'Share of States / UTs in Total Number of Road Accidents - 2021'
8 'Share of States / UTs in Total Number of Road Accidents - 2022'
9 'Share of States / UTs in Total Number of Road Accidents - 2023'
10 'Share of States / UTs in Total Number of Road Accidents - 2024'
11 'Total Number of Accidents Per Lakh Population - 2021'
12 'Total Number of Accidents Per Lakh Population - 2022'
13 'Total Number of Accidents Per Lakh Population - 2023'
14 'Total Number of Accidents Per Lakh Population - 2024'
15 'Total Number of Road Accidents per 10,000 Vehicles - 2022'
16 'Total Number of Road Accidents per 10,000 Km of Roads - 2022 (P)'

In [56]:
display(df.tail())

,Sl. No.,State/UT,State / UT - wise Total Number of Road Accidents during - 2021,State / UT - wise Total Number of Road Accidents during - 2022,State / UT - wise Total Number of Road Accidents during - 2023,State / UT - wise Total Number of Road Accidents during - 2024 - Number,State / UT - wise Total Number of Road Accidents during - 2024 - Rank,Share of States / UTs in Total Number of Road Accidents - 2021,Share of States / UTs in Total Number of Road Accidents - 2022,Share of States / UTs in Total Number of Road Accidents - 2023,Share of States / UTs in Total Number of Road Accidents - 2024,Total Number of Accidents Per Lakh Population - 2021,Total Number of Accidents Per Lakh Population - 2022,Total Number of Accidents Per Lakh Population - 2023,Total Number of Accidents Per Lakh Population - 2024,"Total Number of Road Accidents per 10,000 Vehicles - 2022","Total Number of Road Accidents per 10,000 Km of Roads - 2022 (P)"
32,33,Jammu and Kashmir,5452,6092,6298,5808,18.0,1.3,1.3,1.3,1.2,40.7,45.1,46.3,42.4,27.4,498.7
33,34,Ladakh,236,374,289,264,29.0,0.1,0.1,0.1,0.1,79.5,125.1,96.3,87.4,NaN,612.7
34,35,Lakshadweep,4,3,1,0,36.0,0.0,0.0,0.0,0.0,5.9,4.4,1.4,0.0,1.2,134.7
35,36,Puducherry,1049,1181,1308,1431,24.0,0.3,0.3,0.3,0.3,66.8,73.4,79.5,85.0,9.3,2108.4
36,Total,Total,412432,461312,480583,487707,NaN,100.0,100.0,100.0,100.0,30.3,33.5,34.6,34.8,13.0,810.3

In [57]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   Sl. No.                                                                  37 non-null     object
 1   State/UT                                                                 37 non-null     str
 2   State / UT - wise Total Number of Road Accidents during - 2021           37 non-null     int64
 3   State / UT - wise Total Number of Road Accidents during - 2022           37 non-null     int64
 4   State / UT - wise Total Number of Road Accidents during - 2023           37 non-null     int64
 5   State / UT - wise Total Number of Road Accidents during - 2024 - Number  37 non-null     int64
 6   State / UT - wise Total Number of Road Accidents during - 2024 - Rank    36 non-null     float64
 7   Share of States / UTs in Total Number of Road Accidents - 2021           37 non-null     float64
 8   Share of States / UTs in Total Number of Road Accidents - 2022           37 non-null     float64
 9   Share of States / UTs in Total Number of Road Accidents - 2023           37 non-null     float64
 10  Share of States / UTs in Total Number of Road Accidents - 2024           37 non-null     float64
 11  Total Number of Accidents Per Lakh Population - 2021                     37 non-null     float64
 12  Total Number of Accidents Per Lakh Population - 2022                     37 non-null     float64
 13  Total Number of Accidents Per Lakh Population - 2023                     37 non-null     float64
 14  Total Number of Accidents Per Lakh Population - 2024                     37 non-null     float64
 15  Total Number of Road Accidents per 10,000 Vehicles - 2022                36 non-null     float64
 16  Total Number of Road Accidents per 10,000 Km of Roads - 2022 (P)         37 non-null     float64
dtypes: float64(11), int64(4), object(1), str(1)
memory usage: 5.0+ KB
None

In [58]:
df.columns = [
    "serial no",
    "state_ut",
    "accidents_2021",
    "accidents_2022",
    "accidents_2023",
    "accidents_2024",
    "accidents_2024_rank",
    "share_2021_pct",
    "share_2022_pct",
    "share_2023_pct",
    "share_2024_pct",
    "accidents_per_lakh_pop_2021",
    "accidents_per_lakh_pop_2022",
    "accidents_per_lakh_pop_2023",
    "accidents_per_lakh_pop_2024",
    "accidents_per_10k_vehicles_2022",
    "accidents_per_10k_km_roads_2022"
]

print("Columns renamed successfully")
print(df.columns.tolist())

Columns renamed successfully
['serial no', 'state_ut', 'accidents_2021', 'accidents_2022', 'accidents_2023', 'accidents_2024', 'accidents_2024_rank', 'share_2021_pct', 'share_2022_pct', 'share_2023_pct', 'share_2024_pct', 'accidents_per_lakh_pop_2021', 'accidents_per_lakh_pop_2022', 'accidents_per_lakh_pop_2023', 'accidents_per_lakh_pop_2024', 'accidents_per_10k_vehicles_2022', 'accidents_per_10k_km_roads_2022']

In [59]:
display(df.head())
display(df.tail())

,serial no,state_ut,accidents_2021,accidents_2022,accidents_2023,accidents_2024,accidents_2024_rank,share_2021_pct,share_2022_pct,share_2023_pct,share_2024_pct,accidents_per_lakh_pop_2021,accidents_per_lakh_pop_2022,accidents_per_lakh_pop_2023,accidents_per_lakh_pop_2024,accidents_per_10k_vehicles_2022,accidents_per_10k_km_roads_2022
0,1,Andhra Pradesh,21556,21249,19949,19557,9.0,5.2,4.6,4.2,4.0,40.8,40.1,37.5,36.7,14.2,1098.5
1,2,Arunachal Pradesh,283,227,287,277,27.0,0.1,0.0,0.1,0.1,18.5,14.7,18.4,17.6,6.2,42.8
2,3,Assam,7411,7023,7421,7848,16.0,1.8,1.5,1.5,1.6,21.1,19.9,20.8,21.8,15.6,140.1
3,4,Bihar,9553,10801,11014,11610,14.0,2.3,2.3,2.3,2.4,7.8,8.6,8.7,9.0,9.2,357.5
4,5,Chhattisgarh,12375,13279,13468,14857,11.0,3.0,2.9,2.8,3.0,42.0,44.5,44.6,48.7,17.0,1171.9

,serial no,state_ut,accidents_2021,accidents_2022,accidents_2023,accidents_2024,accidents_2024_rank,share_2021_pct,share_2022_pct,share_2023_pct,share_2024_pct,accidents_per_lakh_pop_2021,accidents_per_lakh_pop_2022,accidents_per_lakh_pop_2023,accidents_per_lakh_pop_2024,accidents_per_10k_vehicles_2022,accidents_per_10k_km_roads_2022
32,33,Jammu and Kashmir,5452,6092,6298,5808,18.0,1.3,1.3,1.3,1.2,40.7,45.1,46.3,42.4,27.4,498.7
33,34,Ladakh,236,374,289,264,29.0,0.1,0.1,0.1,0.1,79.5,125.1,96.3,87.4,NaN,612.7
34,35,Lakshadweep,4,3,1,0,36.0,0.0,0.0,0.0,0.0,5.9,4.4,1.4,0.0,1.2,134.7
35,36,Puducherry,1049,1181,1308,1431,24.0,0.3,0.3,0.3,0.3,66.8,73.4,79.5,85.0,9.3,2108.4
36,Total,Total,412432,461312,480583,487707,NaN,100.0,100.0,100.0,100.0,30.3,33.5,34.6,34.8,13.0,810.3

In [60]:
missing_values = df.isna().sum()

print("Missing values by column:")
print(missing_values[missing_values>0])

Missing values by column:
accidents_2024_rank                1
accidents_per_10k_vehicles_2022    1
dtype: int64

In [61]:
total_mask =(
    df["state_ut"]
    .astype(str)
    .str.lower()
    .eq('total')
)

national_totals =df.loc[total_mask].copy()

state_data = (
    df.loc[~total_mask]
    .copy()
    .reset_index(drop=True)
)

print("National totals shape:", national_totals.shape)
print("State/UT data shape:", state_data.shape)

display(national_totals)
display(state_data.tail())

National totals shape: (1, 17)
State/UT data shape: (36, 17)

,serial no,state_ut,accidents_2021,accidents_2022,accidents_2023,accidents_2024,accidents_2024_rank,share_2021_pct,share_2022_pct,share_2023_pct,share_2024_pct,accidents_per_lakh_pop_2021,accidents_per_lakh_pop_2022,accidents_per_lakh_pop_2023,accidents_per_lakh_pop_2024,accidents_per_10k_vehicles_2022,accidents_per_10k_km_roads_2022
36,Total,Total,412432,461312,480583,487707,NaN,100.0,100.0,100.0,100.0,30.3,33.5,34.6,34.8,13.0,810.3

,serial no,state_ut,accidents_2021,accidents_2022,accidents_2023,accidents_2024,accidents_2024_rank,share_2021_pct,share_2022_pct,share_2023_pct,share_2024_pct,accidents_per_lakh_pop_2021,accidents_per_lakh_pop_2022,accidents_per_lakh_pop_2023,accidents_per_lakh_pop_2024,accidents_per_10k_vehicles_2022,accidents_per_10k_km_roads_2022
31,32,Delhi,4720,5652,5834,5657,19.0,1.1,1.2,1.2,1.2,22.9,27.0,27.3,26.0,4.1,3167.3
32,33,Jammu and Kashmir,5452,6092,6298,5808,18.0,1.3,1.3,1.3,1.2,40.7,45.1,46.3,42.4,27.4,498.7
33,34,Ladakh,236,374,289,264,29.0,0.1,0.1,0.1,0.1,79.5,125.1,96.3,87.4,NaN,612.7
34,35,Lakshadweep,4,3,1,0,36.0,0.0,0.0,0.0,0.0,5.9,4.4,1.4,0.0,1.2,134.7
35,36,Puducherry,1049,1181,1308,1431,24.0,0.3,0.3,0.3,0.3,66.8,73.4,79.5,85.0,9.3,2108.4

In [62]:
missing_vahicle_rate = state_data[
    state_data["accidents_per_10k_vehicles_2022"].isna()
]

display(
    missing_vahicle_rate[
        ["state_ut", "accidents_per_10k_vehicles_2022"]
    ]
)

   state_ut  accidents_per_10k_vehicles_2022
33   Ladakh                              NaN

In [63]:
# Reload the Excel file
df = pd.read_excel(
    data_path,
    sheet_name="Worksheet",
    header=0,
    engine="openpyxl"
)

# Rename all columns
df.columns = [
    "serial_no",
    "state_ut",
    "accidents_2021",
    "accidents_2022",
    "accidents_2023",
    "accidents_2024",
    "accidents_2024_rank",
    "share_2021_pct",
    "share_2022_pct",
    "share_2023_pct",
    "share_2024_pct",
    "accidents_per_lakh_pop_2021",
    "accidents_per_lakh_pop_2022",
    "accidents_per_lakh_pop_2023",
    "accidents_per_lakh_pop_2024",
    "accidents_per_10k_vehicles_2022",
    "accidents_per_10k_km_roads_2022"
]

# Clean State/UT names
df["state_ut"] = df["state_ut"].astype(str).str.strip()

# Separate the Total row
total_mask = df["state_ut"].str.lower().eq("total")

national_totals = df.loc[total_mask].copy()

state_data = (
    df.loc[~total_mask]
    .copy()
    .reset_index(drop=True)
)

print("National totals shape:", national_totals.shape)
print("State/UT data shape:", state_data.shape)
print(state_data.columns.tolist())

National totals shape: (1, 17)
State/UT data shape: (36, 17)
['serial_no', 'state_ut', 'accidents_2021', 'accidents_2022', 'accidents_2023', 'accidents_2024', 'accidents_2024_rank', 'share_2021_pct', 'share_2022_pct', 'share_2023_pct', 'share_2024_pct', 'accidents_per_lakh_pop_2021', 'accidents_per_lakh_pop_2022', 'accidents_per_lakh_pop_2023', 'accidents_per_lakh_pop_2024', 'accidents_per_10k_vehicles_2022', 'accidents_per_10k_km_roads_2022']

In [64]:
integer_columns = [
    "serial_no",
    "accidents_2021",
    "accidents_2022",
    "accidents_2023",
    "accidents_2024",
    "accidents_2024_rank",
]

float_columns = [
    "share_2021_pct",
    "share_2021_pct",
    "share_2021_pct",
    "share_2021_pct",
    "accidents_per_lakh_pop_2021",
    "accidents_per_lakh_pop_2022",
    "accidents_per_lakh_pop_2023",
    "accidents_per_lakh_pop_2024",
    "accidents_per_10k_vehicles_2022",
    "accidents_per_10k_km_roads_2022"
    
]

for column in integer_columns:
    state_data[column]= pd.to_numeric(
        state_data[column],
        errors="coerce"
    ).astype("Int64")

for column in float_columns:
    state_data[column] = pd.to_numeric(
        state_data[column],
        errors="coerce"
    ).astype("Float64")

state_data["state_ut"] = state_data["state_ut"].str.strip()

print(state_data.dtypes)

serial_no                            Int64
state_ut                               str
accidents_2021                       Int64
accidents_2022                       Int64
accidents_2023                       Int64
accidents_2024                       Int64
accidents_2024_rank                  Int64
share_2021_pct                     Float64
share_2022_pct                     float64
share_2023_pct                     float64
share_2024_pct                     float64
accidents_per_lakh_pop_2021        Float64
accidents_per_lakh_pop_2022        Float64
accidents_per_lakh_pop_2023        Float64
accidents_per_lakh_pop_2024        Float64
accidents_per_10k_vehicles_2022    Float64
accidents_per_10k_km_roads_2022    Float64
dtype: object

In [65]:
print("Shape:", state_data.shape)

print("\nMissing values:")
print(state_data.isna().sum()[state_data.isna().sum() > 0])

display(state_data.head())

Shape: (36, 17)

Missing values:
accidents_per_10k_vehicles_2022    1
dtype: int64

,serial_no,state_ut,accidents_2021,accidents_2022,accidents_2023,accidents_2024,accidents_2024_rank,share_2021_pct,share_2022_pct,share_2023_pct,share_2024_pct,accidents_per_lakh_pop_2021,accidents_per_lakh_pop_2022,accidents_per_lakh_pop_2023,accidents_per_lakh_pop_2024,accidents_per_10k_vehicles_2022,accidents_per_10k_km_roads_2022
0,1,Andhra Pradesh,21556,21249,19949,19557,9,5.2,4.6,4.2,4.0,40.8,40.1,37.5,36.7,14.2,1098.5
1,2,Arunachal Pradesh,283,227,287,277,27,0.1,0.0,0.1,0.1,18.5,14.7,18.4,17.6,6.2,42.8
2,3,Assam,7411,7023,7421,7848,16,1.8,1.5,1.5,1.6,21.1,19.9,20.8,21.8,15.6,140.1
3,4,Bihar,9553,10801,11014,11610,14,2.3,2.3,2.3,2.4,7.8,8.6,8.7,9.0,9.2,357.5
4,5,Chhattisgarh,12375,13279,13468,14857,11,3.0,2.9,2.8,3.0,42.0,44.5,44.6,48.7,17.0,1171.9

### Missing-value decision

The `accidents_per_10k_vehicles_2022` value is unavailable for one Union
Territory. The value has been retained as missing rather than imputed,
because substituting an estimated value could distort normalized rankings.

missing_vehicle_rate = state_data.loc[
    state_data["accidents_per_10k_vehicles_2022"].isna(),
    ["state_ut","accidents_per_10k_vehicles_2022"]
]

display(misssing_vehicle_rate)

In [66]:
missing_vehicle_rate = state_data.loc[
    state_data["accidents_per_10k_vehicles_2022"].isna(),
    ["state_ut", "accidents_per_10k_vehicles_2022"]
]

display(missing_vehicle_rate)

   state_ut  accidents_per_10k_vehicles_2022
33   Ladakh                             <NA>

In [67]:
state_data["vehicle_rate_available"] = (
    state_data["accidents_per_10k_vehicles_2022"].notna()
)

display(
    state_data.loc[
        ~state_data["vehicle_rate_available"],
        ["state_ut", "vehicle_rate_available"]
    ]
)

   state_ut  vehicle_rate_available
33   Ladakh                   False

In [68]:
state_data["yoy_change_2024_pct"] = (
    (
        state_data["accidents_2024"]
        - state_data["accidents_2023"]
    )
    / state_data["accidents_2023"]
    *100
).round(2)

display(
    state_data[
        [
            "state_ut",
            "accidents_2023",
            "accidents_2024",
            "yoy_change_2024_pct"
        ]
    ].head()
)

            state_ut  accidents_2023  accidents_2024  yoy_change_2024_pct
0     Andhra Pradesh           19949           19557                -1.97
1  Arunachal Pradesh             287             277                -3.48
2              Assam            7421            7848                 5.75
3              Bihar           11014           11610                 5.41
4       Chhattisgarh           13468           14857                10.31

In [69]:
state_data["cagr_2021_2024_pct"] = (
    (
        state_data["accidents_2024"]
        / state_data["accidents_2021"]
    ) ** (1 / 3)
    - 1
) * 100

state_data["cagr_2021_2024_pct"] = (
    state_data["cagr_2021_2024_pct"].round(2)
)

display(
    state_data[
        [
            "state_ut",
            "accidents_2021",
            "accidents_2024",
            "cagr_2021_2024_pct"
        ]
    ].head()
)

            state_ut  accidents_2021  accidents_2024  cagr_2021_2024_pct
0     Andhra Pradesh           21556           19557               -3.19
1  Arunachal Pradesh             283             277               -0.71
2              Assam            7411            7848                1.93
3              Bihar            9553           11610                6.72
4       Chhattisgarh           12375           14857                6.28

In [70]:
print("Updated shape:", state_data.shape)

print("\nNew columns:")
print(
    state_data[
        [
            "vehicle_rate_available",
            "yoy_change_2024_pct",
            "cagr_2021_2024_pct"
        ]
    ].dtypes
)

display(
    state_data[
        [
            "state_ut",
            "accidents_2024",
            "yoy_change_2024_pct",
            "cagr_2021_2024_pct",
            "vehicle_rate_available"
        ]
    ].head(10)
)

Updated shape: (36, 20)

New columns:
vehicle_rate_available       bool
yoy_change_2024_pct       Float64
cagr_2021_2024_pct        Float64
dtype: object

,state_ut,accidents_2024,yoy_change_2024_pct,cagr_2021_2024_pct,vehicle_rate_available
0,Andhra Pradesh,19557,-1.97,-3.19,True
1,Arunachal Pradesh,277,-3.48,-0.71,True
2,Assam,7848,5.75,1.93,True
3,Bihar,11610,5.41,6.72,True
4,Chhattisgarh,14857,10.31,6.28,True
5,Goa,2682,-5.76,-1.99,True
6,Gujarat,15588,-4.65,0.87,True
7,Haryana,9806,-6.28,-0.43,True
8,Himachal Pradesh,2156,-4.31,-3.56,True
9,Jharkhand,5196,-2.24,3.2,True

In [71]:
region_map = {
    # North
    "Haryana": "North",
    "Himachal Pradesh": "North",
    "Punjab": "North",
    "Rajasthan": "North",
    "Uttar Pradesh": "North",
    "Uttarakhand": "North",

    # South
    "Andhra Pradesh": "South",
    "Karnataka": "South",
    "Kerala": "South",
    "Tamil Nadu": "South",
    "Telangana": "South",

    # East
    "Bihar": "East",
    "Jharkhand": "East",
    "Odisha": "East",
    "West Bengal": "East",

    # West
    "Goa": "West",
    "Gujarat": "West",
    "Maharashtra": "West",

    # Central
    "Chhattisgarh": "Central",
    "Madhya Pradesh": "Central",

    # Northeast
    "Arunachal Pradesh": "Northeast",
    "Assam": "Northeast",
    "Manipur": "Northeast",
    "Meghalaya": "Northeast",
    "Mizoram": "Northeast",
    "Nagaland": "Northeast",
    "Sikkim": "Northeast",
    "Tripura": "Northeast",

    # Union Territories
    "Andaman and Nicobar Islands": "Union Territory",
    "Chandigarh": "Union Territory",
    "Dadra and Nagar Haveli and Daman and Diu": "Union Territory",
    "Delhi": "Union Territory",
    "Jammu and Kashmir": "Union Territory",
    "Ladakh": "Union Territory",
    "Lakshadweep": "Union Territory",
    "Puducherry": "Union Territory"
}

state_data["region"] = state_data["state_ut"].map(region_map)

print("Updated shape:", state_data.shape)

display(
    state_data[
        ["state_ut", "region"]
    ].sort_values(["region", "state_ut"])
)

Updated shape: (36, 21)

                                    state_ut           region
4                               Chhattisgarh          Central
12                            Madhya Pradesh          Central
3                                      Bihar             East
9                                  Jharkhand             East
18                                    Odisha             East
27                               West Bengal             East
7                                    Haryana            North
8                           Himachal Pradesh            North
19                                    Punjab            North
20                                 Rajasthan            North
26                             Uttar Pradesh            North
25                               Uttarakhand            North
1                          Arunachal Pradesh        Northeast
2                                      Assam        Northeast
14                                   Manipur        Northeast
15                                 Meghalaya        Northeast
16                                   Mizoram        Northeast
17                                  Nagaland        Northeast
21                                    Sikkim        Northeast
24                                   Tripura        Northeast
0                             Andhra Pradesh            South
10                                 Karnataka            South
11                                    Kerala            South
22                                Tamil Nadu            South
23                                 Telangana            South
28               Andaman and Nicobar Islands  Union Territory
29                                Chandigarh  Union Territory
30  Dadra and Nagar Haveli and Daman and Diu  Union Territory
31                                     Delhi  Union Territory
32                         Jammu and Kashmir  Union Territory
33                                    Ladakh  Union Territory
34                               Lakshadweep  Union Territory
35                                Puducherry  Union Territory
5                                        Goa             West
6                                    Gujarat             West
13                               Maharashtra             West

In [72]:
unmapped_states = state_data.loc[
    state_data["region"].isna(),
    ["state_ut"]
]

print("Number of unmapped State/UT names:", len(unmapped_states))
display(unmapped_states)

Number of unmapped State/UT names: 0

Empty DataFrame
Columns: [state_ut]
Index: []

In [73]:
print(state_data["region"].value_counts())

region
Northeast          8
Union Territory    8
North              6
South              5
East               4
West               3
Central            2
Name: count, dtype: int64

### Reshape accident counts for trend analysis

The original dataset stores 2021–2024 accident counts in separate columns.
A long-format table is created so each State/UT and year has one observation,
making the data suitable for time-series charts and dashboard filters.

In [74]:
accident_year_columns = [
    "accidents_2021",
    "accidents_2022",
    "accidents_2023",
    "accidents_2024"
]

trend_data = state_data.melt(
    id_vars=["serial_no", "state_ut", "region"],
    value_vars=accident_year_columns,
    var_name="year",
    value_name="accident_count"
)

display(trend_data.head(10))
print("Trend data shape:", trend_data.shape)

   serial_no           state_ut     region            year  accident_count
0          1     Andhra Pradesh      South  accidents_2021           21556
1          2  Arunachal Pradesh  Northeast  accidents_2021             283
2          3              Assam  Northeast  accidents_2021            7411
3          4              Bihar       East  accidents_2021            9553
4          5       Chhattisgarh    Central  accidents_2021           12375
5          6                Goa       West  accidents_2021            2849
6          7            Gujarat       West  accidents_2021           15186
7          8            Haryana      North  accidents_2021            9933
8          9   Himachal Pradesh      North  accidents_2021            2404
9         10          Jharkhand       East  accidents_2021            4728

Trend data shape: (144, 5)

In [75]:
trend_data["year"] = (
    trend_data["year"]
    .str.replace("accidents_", "", regex=False)
    .astype("Int64")
)

trend_data["accident_count"] = (
    pd.to_numeric(
        trend_data["accident_count"],
        errors="coerce"
    )
    .astype("Int64")
)

trend_data = trend_data.sort_values(
    ["state_ut", "year"]
).reset_index(drop=True)

display(trend_data.head(12))
print(trend_data.dtypes)

,serial_no,state_ut,region,year,accident_count
0,29,Andaman and Nicobar Islands,Union Territory,2021,115
1,29,Andaman and Nicobar Islands,Union Territory,2022,141
2,29,Andaman and Nicobar Islands,Union Territory,2023,143
3,29,Andaman and Nicobar Islands,Union Territory,2024,135
4,1,Andhra Pradesh,South,2021,21556
5,1,Andhra Pradesh,South,2022,21249
6,1,Andhra Pradesh,South,2023,19949
7,1,Andhra Pradesh,South,2024,19557
8,2,Arunachal Pradesh,Northeast,2021,283
9,2,Arunachal Pradesh,Northeast,2022,227
10,2,Arunachal Pradesh,Northeast,2023,287
11,2,Arunachal Pradesh,Northeast,2024,277

serial_no         Int64
state_ut            str
region              str
year              Int64
accident_count    Int64
dtype: object

In [76]:
print("Number of rows:", len(trend_data))
print("Number of State/UTs:", trend_data["state_ut"].nunique())
print("Years:", sorted(trend_data["year"].unique().tolist()))

print("\nMissing values:")
print(
    trend_data.isna().sum()[
        trend_data.isna().sum() > 0
    ]
)

Number of rows: 144
Number of State/UTs: 36
Years: [2021, 2022, 2023, 2024]

Missing values:
Series([], dtype: int64)

### Data validation

State/UT accident counts are summed for each year and compared with the
national Total row from the source file. A difference of zero confirms
that no records were lost or duplicated during cleaning.

In [77]:
year_columns = {
    2021: "accidents_2021",
    2022: "accidents_2022",
    2023: "accidents_2023",
    2024: "accidents_2024"
}

validation_rows = []

for year, column in year_columns.items():
    calculated_total = int(
        pd.to_numeric(
            state_data[column],
            errors="coerce"
        ).sum()
    )

    reported_total = int(
        pd.to_numeric(
            national_totals[column],
            errors="coerce"
        ).iloc[0]
    )

    validation_rows.append({
        "year": year,
        "calculated_state_total": calculated_total,
        "reported_national_total": reported_total,
        "difference": calculated_total - reported_total,
        "matches": calculated_total == reported_total
    })

validation_df = pd.DataFrame(validation_rows)

display(validation_df)

   year  calculated_state_total  reported_national_total  difference  matches
0  2021                  412432                   412432           0     True
1  2022                  461312                   461312           0     True
2  2023                  480583                   480583           0     True
3  2024                  487707                   487707           0     True

In [78]:
assert validation_df["matches"].all(), (
    "Validation failed: State/UT totals do not match "
    "the reported national totals."
)

print("Validation passed: all yearly totals match.")

Validation passed: all yearly totals match.

### Export cleaned datasets

Three processed files are exported:

1. `accidents_cleaned.csv` — State/UT-level dataset with rates, regions and derived metrics
2. `accidents_trend_long.csv` — long-format accident counts for trend charts
3. `national_totals.csv` — reported national totals kept separately for validation

In [79]:
processed_dir = Path("../data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

cleaned_output_path = processed_dir / "accidents_cleaned.csv"
trend_output_path = processed_dir / "accidents_trend_long.csv"
totals_output_path = processed_dir / "national_totals.csv"

state_data = state_data.sort_values("serial_no").reset_index(drop=True)

state_data.to_csv(
    cleaned_output_path,
    index=False
)

trend_data.to_csv(
    trend_output_path,
    index=False
)

national_totals.to_csv(
    totals_output_path,
    index=False
)

print("Files exported successfully:")
print(cleaned_output_path.resolve())
print(trend_output_path.resolve())
print(totals_output_path.resolve())

Files exported successfully:
/Users/sourabh/Desktop/road-accidents-india-analysis/data/processed/accidents_cleaned.csv
/Users/sourabh/Desktop/road-accidents-india-analysis/data/processed/accidents_trend_long.csv
/Users/sourabh/Desktop/road-accidents-india-analysis/data/processed/national_totals.csv

In [80]:
exported_cleaned = pd.read_csv(cleaned_output_path)
exported_trend = pd.read_csv(trend_output_path)
exported_totals = pd.read_csv(totals_output_path)

print("accidents_cleaned.csv:", exported_cleaned.shape)
print("accidents_trend_long.csv:", exported_trend.shape)
print("national_totals.csv:", exported_totals.shape)

print("\nFiles exist:")
print("Cleaned:", cleaned_output_path.exists())
print("Trend:", trend_output_path.exists())
print("Totals:", totals_output_path.exists())

accidents_cleaned.csv: (36, 21)
accidents_trend_long.csv: (144, 5)
national_totals.csv: (1, 17)

Files exist:
Cleaned: True
Trend: True
Totals: True